name: friday
description: Your Personal Class Manager Assistant, It'll never let you miss another assignment deadline or upcoming test.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  provider: ^4.3.3
  fluttertoast: ^7.1.6
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_icons: ^1.1.0
  cupertino_icons: ^0.1.3
  cloud_firestore: ^1.0.3
  firebase_auth: ^1.0.1
  email_validator: '^1.0.0'
  google_sign_in:
  uuid: ^3.0.1
  image_picker:
  url_launcher: ^6.0.2
  firebase_storage: ^8.0.1
  path_provider:
  date_time_picker: ^2.0.0
  table_calendar: ^3.0.0
  flutter_login_facebook: ^1.5.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
